### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DaLLuZZ** [DaLLuZZ/CyberTimer#17]
- [x] Hookzone: закрывается меню (не закрывать меню)
- [x] первый рекорд - N/A, ссылки в дискорде
- [x] TeleToStage зона
- [x] Стейдж
- [ ] info_player_* для ботов
- [ ] SL как CS
- [ ] SL в ck_playeroptions
- [ ] оптимизация ck_playeroptions
- [ ] Central Hud: `<span class=\"fontSize-l\">`
- [ ] проверить килл таймера централ спида
- [x] проверить закрытие дескрипторов датапаков для загрузки реплеев по фтп, если таймер убит
- [ ] запись престрейфов в низких стартовых/стейджевых зонах
- [x] Посмотреть OnPlayerRunCMD, убрать лишний код
- [x] [FS] UNRANKED, [HSW] [SURFGOD]
- [x] подумать над OnGameFrame() вместо OnPlayerRunCmd для некоторых вещей
- [x] убрать проверку на ноуклип при создании лока
- [x] в db_insertzone и ... cheap при отсутствии коннекта к саб - сообщение в чат зонеру
- [x] не давать +60 поинтов, если срцп перебил его же холдер
- [x] если нет срцп - первое прохождение считать за срцп
- [x] Перенести определение тикрейта плагинами на старт карты (желательно с реквестфреймом перед коннектами)
- [ ] Оптимизация форматирования строк (FormatEx, где возможно)
- [x] Проверить аплоад реплея ласт стейджа, если перебит и стейдж, и ср карты в одном ране
- [ ] Посмотреть PlayerSpawn()
- [x] Посмотреть maxspeed-зону (лимит  всегда 2500  (смысл?) + может(?) быть на всей карте)
- [x] Посмотреть anti-jump зону (карта surf_zen - можно бхопить в зоне)
- [ ] Посмотреть стартзону бонуса 2 на юникорне (таймер не идёт, мб нет вызова cl_onstarttimerpress)
- [x] Проверить значение переменной g_bGR_FFD в случае, если реплеи отсутствуют на удалённом сервере
- [x] Добавить запись престрейфа (останавливать запись не в endtouch, а в starttouch, т.е. при возвращении на старт)
- [x] Хранить коды ошибок CURLа в строке, выводить в sm_ckdebug, очищать в UpdateGlobalReplays() 
- [ ] рестор позиции (начиная с 4го тира)
- [ ] кросс-сервер анонсмент рекордов
- [ ] https://github.com/shavitush/bhoptimer/pull/931
- [ ] https://blog.momentum-mod.org/post/146131743729/how-the-momentum-mod-timer-works-how-to-get-a
